servers:
  server-example:
    replicas: 3
    image: docker-local:5000/server
    port: 50051
    env:
      - name: DATABASE_URL
        value: postgres://admin:password@db/books
  server-hello-world:
    replicas: 3
    image: docker-local:5000/server-hello-world
    port: 50051
  nginx-grpc:
    replicas: 3
    image: docker-local:5000/nginx-grpc
    port: 50051