apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container.name }}
  labels:
    app: {{ .Values.container.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.container.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}
          env:
          {{- range .Values.container.env }}
            - name: {{ .name }}
              value: {{ .value }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.container.port }}
              name: {{ .Values.container.name }}